#!/bin/sh
wget    -P amicorpus/EN2001a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001a/audio/EN2001a.Mix-Headset.wav
wget    -P amicorpus/EN2001a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001a/audio/EN2001a.Headset-0.wav
wget    -P amicorpus/EN2001a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001a/audio/EN2001a.Headset-1.wav
wget    -P amicorpus/EN2001a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001a/audio/EN2001a.Headset-2.wav
wget    -P amicorpus/EN2001a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001a/audio/EN2001a.Headset-3.wav
wget    -P amicorpus/EN2001a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001a/audio/EN2001a.Headset-4.wav
wget    -P amicorpus/EN2001b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001b/audio/EN2001b.Mix-Headset.wav
wget    -P amicorpus/EN2001b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001b/audio/EN2001b.Headset-0.wav
wget    -P amicorpus/EN2001b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001b/audio/EN2001b.Headset-1.wav
wget    -P amicorpus/EN2001b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001b/audio/EN2001b.Headset-2.wav
wget    -P amicorpus/EN2001b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001b/audio/EN2001b.Headset-3.wav
wget    -P amicorpus/EN2001d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001d/audio/EN2001d.Mix-Headset.wav
wget    -P amicorpus/EN2001d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001d/audio/EN2001d.Headset-0.wav
wget    -P amicorpus/EN2001d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001d/audio/EN2001d.Headset-1.wav
wget    -P amicorpus/EN2001d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001d/audio/EN2001d.Headset-2.wav
wget    -P amicorpus/EN2001d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001d/audio/EN2001d.Headset-3.wav
wget    -P amicorpus/EN2001d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001d/audio/EN2001d.Headset-4.wav
wget    -P amicorpus/EN2001e/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001e/audio/EN2001e.Mix-Headset.wav
wget    -P amicorpus/EN2001e/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001e/audio/EN2001e.Headset-0.wav
wget    -P amicorpus/EN2001e/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001e/audio/EN2001e.Headset-1.wav
wget    -P amicorpus/EN2001e/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001e/audio/EN2001e.Headset-2.wav
wget    -P amicorpus/EN2001e/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001e/audio/EN2001e.Headset-3.wav
wget    -P amicorpus/EN2001e/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001e/audio/EN2001e.Headset-4.wav
wget    -P amicorpus/EN2002a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002a/audio/EN2002a.Mix-Headset.wav
wget    -P amicorpus/EN2002a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002a/audio/EN2002a.Headset-0.wav
wget    -P amicorpus/EN2002a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002a/audio/EN2002a.Headset-1.wav
wget    -P amicorpus/EN2002a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002a/audio/EN2002a.Headset-2.wav
wget    -P amicorpus/EN2002a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002a/audio/EN2002a.Headset-3.wav
wget    -P amicorpus/EN2002b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002b/audio/EN2002b.Mix-Headset.wav
wget    -P amicorpus/EN2002b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002b/audio/EN2002b.Headset-0.wav
wget    -P amicorpus/EN2002b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002b/audio/EN2002b.Headset-1.wav
wget    -P amicorpus/EN2002b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002b/audio/EN2002b.Headset-2.wav
wget    -P amicorpus/EN2002b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002b/audio/EN2002b.Headset-3.wav
wget    -P amicorpus/EN2002c/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002c/audio/EN2002c.Mix-Headset.wav
wget    -P amicorpus/EN2002c/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002c/audio/EN2002c.Headset-0.wav
wget    -P amicorpus/EN2002c/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002c/audio/EN2002c.Headset-1.wav
wget    -P amicorpus/EN2002c/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002c/audio/EN2002c.Headset-2.wav
wget    -P amicorpus/EN2002c/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002c/audio/EN2002c.Headset-3.wav
wget    -P amicorpus/EN2002d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002d/audio/EN2002d.Mix-Headset.wav
wget    -P amicorpus/EN2002d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002d/audio/EN2002d.Headset-0.wav
wget    -P amicorpus/EN2002d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002d/audio/EN2002d.Headset-1.wav
wget    -P amicorpus/EN2002d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002d/audio/EN2002d.Headset-2.wav
wget    -P amicorpus/EN2002d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002d/audio/EN2002d.Headset-3.wav
wget    -P amicorpus/EN2006a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006a/audio/EN2006a.Mix-Headset.wav
wget    -P amicorpus/EN2006a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006a/audio/EN2006a.Headset-0.wav
wget    -P amicorpus/EN2006a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006a/audio/EN2006a.Headset-1.wav
wget    -P amicorpus/EN2006a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006a/audio/EN2006a.Headset-2.wav
wget    -P amicorpus/EN2006a/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006a/audio/EN2006a.Headset-3.wav
wget    -P amicorpus/EN2006b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006b/audio/EN2006b.Mix-Headset.wav
wget    -P amicorpus/EN2006b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006b/audio/EN2006b.Headset-0.wav
wget    -P amicorpus/EN2006b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006b/audio/EN2006b.Headset-1.wav
wget    -P amicorpus/EN2006b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006b/audio/EN2006b.Headset-2.wav
wget    -P amicorpus/EN2006b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006b/audio/EN2006b.Headset-3.wav
wget    -P amicorpus/EN2009b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009b/audio/EN2009b.Mix-Headset.wav
wget    -P amicorpus/EN2009b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009b/audio/EN2009b.Headset-0.wav
wget    -P amicorpus/EN2009b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009b/audio/EN2009b.Headset-1.wav
wget    -P amicorpus/EN2009b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009b/audio/EN2009b.Headset-2.wav
wget    -P amicorpus/EN2009b/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009b/audio/EN2009b.Headset-3.wav
wget    -P amicorpus/EN2009c/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009c/audio/EN2009c.Mix-Headset.wav
wget    -P amicorpus/EN2009c/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009c/audio/EN2009c.Headset-0.wav
wget    -P amicorpus/EN2009c/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009c/audio/EN2009c.Headset-1.wav
wget    -P amicorpus/EN2009c/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009c/audio/EN2009c.Headset-2.wav
wget    -P amicorpus/EN2009c/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009c/audio/EN2009c.Headset-3.wav
wget    -P amicorpus/EN2009d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009d/audio/EN2009d.Mix-Headset.wav
wget    -P amicorpus/EN2009d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009d/audio/EN2009d.Headset-0.wav
wget    -P amicorpus/EN2009d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009d/audio/EN2009d.Headset-1.wav
wget    -P amicorpus/EN2009d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009d/audio/EN2009d.Headset-2.wav
wget    -P amicorpus/EN2009d/audio http://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009d/audio/EN2009d.Headset-3.wav
wget http://groups.inf.ed.ac.uk/ami/download/temp/amiBuild-19136-Thu-Oct-15-2015.manifest.txt
wget http://groups.inf.ed.ac.uk/ami/download/temp/../Creative-Commons-Attribution-NonCommercial-ShareAlike-2.5.txt
